### ISSUE TITLE
PlatformException(Zoom SDK error, ZoomSDK is not initialized, null, null)

### ISSUE THREAD

**Issue by GowthamScripts** [25LucasAnselmo/gr_zoom#11]
═══════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel plugins.webcare/zoom_event_stream:
PlatformException(Zoom SDK error, ZoomSDK is not initialized, null, null)

**Comment by 25LucasAnselmo** [comment]
Which version are you using?

**Comment by GowthamScripts** [comment]
1.2.0+4

**Comment by GowthamScripts** [comment]
i was update +5 but this code not working 
 String platformVersion = '';
    try {
      platformVersion =
          await zoom.getPlatformVersion() ?? 'Unknown platform version';
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    print(platformVersion);

**Comment by GowthamScripts** [comment]
var meetingOptions = ZoomMeetingOptions(
        userId:
            'username', //pass username for join meeting only --- Any name eg:- EVILRATT.
        meetingId: 'xxxxxxx', //pass meeting id for join meeting only
        meetingPassword: 'xxxx', //pass meeting password for join meeting only
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "true",
        disableShare: "true",
        noAudio: "false",
        noDisconnectAudio: "false");

    zoom.init(zoomOptions).then((results) {
      print(results[0]);
      if (results[0] == 0) {
        zoom.onMeetingStateChanged.listen((status) {
          print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
        });
        print("listen on event channel");
        zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
          print(joinMeetingResult);
        });
      }
    }).catchError((error) {
      print("[Error Generated] : " + error);
    });


output
flutter: listen on event channel
flutter: true
4
flutter: [Meeting Status Stream] : MEETING_STATUS_CONNECTING - Connect to the meeting server
flutter: [Meeting Status Stream] : MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, leave meeting status
flutter: [Meeting Status Stream] : MEETING_STATUS_FAILED - Failed to connect the meeting server
flutter: [Meeting Status Stream] : MEETING_STATUS_ENDED - Meeting ends

**Comment by Anuj01111** [comment]
How do I use and create JWT tokens? Please tell me.
Help Me
