### ISSUE TITLE
PlatformException(Zoom SDK error, ZoomSDK is not initialized, null, null)

### ISSUE THREAD

**Issue by GowthamScripts** [25LucasAnselmo/gr_zoom#12]
ZoomOptions zoomOptions = ZoomOptions(
      domain: "zoom.us",
      appKey: "xxxxxxx", //API KEY FROM ZOOM - Sdk API Key
      appSecret:
          "xxxxxxxxxxxxxxxxxxx", //API SECRET FROM ZOOM - Sdk API Secret
    );

var meetingOptions = ZoomMeetingOptions(
        userId:
            'username', //pass username for join meeting only --- Any name eg:- EVILRATT.
        meetingId: '', //pass meeting id for join meeting only
        meetingPassword: '', //pass meeting password for join meeting only
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "true",
        disableShare: "true",
        noAudio: "false",
        noDisconnectAudio: "false");

zoom.init(zoomOptions).then((results) {
      print(results);
      if (results[0] == 0) {
        zoom.onMeetingStateChanged.listen((status) {
          print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
        });
        print("listen on event channel");
        zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
          print(joinMeetingResult);
        });
      }
    }).catchError((error) {
      print("[Error Generated] : " + error);
    });

results => [1,0]

**Comment by 25LucasAnselmo** [comment]
> ZoomOptions zoomOptions = ZoomOptions( domain: "zoom.us", appKey: "xxxxxxx", //API KEY FROM ZOOM - Sdk API Key appSecret: "xxxxxxxxxxxxxxxxxxx", //API SECRET FROM ZOOM - Sdk API Secret );
> 
> var meetingOptions = ZoomMeetingOptions( userId: 'username', //pass username for join meeting only --- Any name eg:- EVILRATT. meetingId: '', //pass meeting id for join meeting only meetingPassword: '', //pass meeting password for join meeting only disableDialIn: "true", disableDrive: "true", disableInvite: "true", disableShare: "true", noAudio: "false", noDisconnectAudio: "false");
> 
> zoom.init(zoomOptions).then((results) { print(results); if (results[0] == 0) { zoom.onMeetingStateChanged.listen((status) { print("[Meeting Status Stream] : " + status[0] + " - " + status[1]); }); print("listen on event channel"); zoom.joinMeeting(meetingOptions).then((joinMeetingResult) { print(joinMeetingResult); }); } }).catchError((error) { print("[Error Generated] : " + error); });
> 
> results => [1,0]

If you are using version +1.2, appkey and appSecret authentication will not work. You have to use jwtToken
