### ISSUE TITLE
Meeting status connecting and then immediately disconnecting Meeting 

### ISSUE THREAD

**Issue by GowthamScripts** [25LucasAnselmo/gr_zoom#13]
```
zoomClass() async {
    ZoomOptions zoomOptions = ZoomOptions(
      domain: "zoom.us",
      jwtToken: generateSignature(
          'xxxxxxxx', 'xxxxxxxxxxxxxxxxxxx'),
    );

    var meetingOptions = ZoomMeetingOptions(
        userId:
            'username',
        meetingId: 'xxxxxxxxx', //pass meeting id for join meeting only
        meetingPassword: 'xxxxxxx', //pass meeting password for join meeting only
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "true",
        disableShare: "true",
        noAudio: "false",
        noDisconnectAudio: "false");

    zoom.init(zoomOptions).then((results) {
      print(results[0]);
      if (results[0] == 0) {
        zoom.onMeetingStateChanged.listen((status) {
          print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
        });
        print("listen on event channel");
        zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
          print('joinMeetingResult');
          print(joinMeetingResult);
        }).catchError((error, stackTrace) {
          print('error');
          print(error);
        });
      }
    }).catchError((error) {
      print("[Error Generated] : " + error);
    });
  }

```
output: 
```
flutter: [Meeting Status Stream] : MEETING_STATUS_CONNECTING - Connect to the meeting server
flutter: [Meeting Status Stream] : MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, leave meeting status
flutter: [Meeting Status Stream] : MEETING_STATUS_FAILED - Failed to connect the meeting server
flutter: [Meeting Status Stream] : MEETING_STATUS_ENDED - Meeting ends
```

Version : 1.2.0+5

Please assist urgently.

**Comment by 25LMartins** [comment]
> ```
> zoomClass() async {
>   ZoomOptions zoomOptions = ZoomOptions(
>     domain: "zoom.us",
>     jwtToken: generateSignature(
>         'xxxxxxxx', 'xxxxxxxxxxxxxxxxxxx'),
>   );
> 
>   var meetingOptions = ZoomMeetingOptions(
>       userId:
>           'username',
>       meetingId: 'xxxxxxxxx', //pass meeting id for join meeting only
>       meetingPassword: 'xxxxxxx', //pass meeting password for join meeting only
>       disableDialIn: "true",
>       disableDrive: "true",
>       disableInvite: "true",
>       disableShare: "true",
>       noAudio: "false",
>       noDisconnectAudio: "false");
> 
>   zoom.init(zoomOptions).then((results) {
>     print(results[0]);
>     if (results[0] == 0) {
>       zoom.onMeetingStateChanged.listen((status) {
>         print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
>       });
>       print("listen on event channel");
>       zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
>         print('joinMeetingResult');
>         print(joinMeetingResult);
>       }).catchError((error, stackTrace) {
>         print('error');
>         print(error);
>       });
>     }
>   }).catchError((error) {
>     print("[Error Generated] : " + error);
>   });
> }
> ```
> 
> output:
> 
> ```
> flutter: [Meeting Status Stream] : MEETING_STATUS_CONNECTING - Connect to the meeting server
> flutter: [Meeting Status Stream] : MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, leave meeting status
> flutter: [Meeting Status Stream] : MEETING_STATUS_FAILED - Failed to connect the meeting server
> flutter: [Meeting Status Stream] : MEETING_STATUS_ENDED - Meeting ends
> ```
> 
> Version : 1.2.0+5
> 
> Please assist urgently.

Check your jwtToken, the issue seems problem like this
