### ISSUE TITLE
"How do I use and create JWT tokens? Please tell me."

### ISSUE THREAD

**Issue by Anuj01111** [25LucasAnselmo/gr_zoom#14]
"How do I use and create JWT tokens? Please tell me."

**Comment by 25LMartins** [comment]
> "How do I use and create JWT tokens? Please tell me."

Take a look on Zoom meeting sdk doc:

https://developers.zoom.us/docs/meeting-sdk/auth/

**Comment by 25LMartins** [comment]
> "How do I use and create JWT tokens? Please tell me."

https://medium.com/@purushottaminorbit26/solving-the-zoom-meeting-sdk-upgrade-issue-with-jwt-token-and-sdk-initialization-ios-2e88fc553b2
