### ISSUE TITLE
var meetingOptions = ZoomMeetingOptions(

### ISSUE THREAD

**Issue by GowthamScripts** [25LucasAnselmo/gr_zoom#15]
var meetingOptions = ZoomMeetingOptions(
        userId:
            'username', //pass username for join meeting only --- Any name eg:- EVILRATT.
        meetingId: 'xxxxxxx', //pass meeting id for join meeting only
        meetingPassword: 'xxxx', //pass meeting password for join meeting only
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "true",
        disableShare: "true",
        noAudio: "false",
        noDisconnectAudio: "false");

    zoom.init(zoomOptions).then((results) {
      print(results[0]);
      if (results[0] == 0) {
        zoom.onMeetingStateChanged.listen((status) {
          print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
        });
        print("listen on event channel");
        zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
          print(joinMeetingResult);
        });
      }
    }).catchError((error) {
      print("[Error Generated] : " + error);
    });

output
flutter: listen on event channel
flutter: true
4
flutter: [Meeting Status Stream] : MEETING_STATUS_CONNECTING - Connect to the meeting server
flutter: [Meeting Status Stream] : MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, leave meeting status
flutter: [Meeting Status Stream] : MEETING_STATUS_FAILED - Failed to connect the meeting server
flutter: [Meeting Status Stream] : MEETING_STATUS_ENDED - Meeting ends

_Originally posted by @gowthaman13 in https://github.com/25LucasAnselmo/gr_zoom/issues/11#issuecomment-1977081212_

**Comment by 25LMartins** [comment]
var meetingOptions = new ZoomMeetingOptions(
        zoomAccessToken: ZAK_TOKEN, // See on zoom meeting website how to use
        zoomToken: ZOOM_TOKEN,
        userId: USERNAME,
        displayName: DISPLAYED_NAME,
        meetingId: MEETING_ID,
        meetingPassword: MEETING_PASS, // Only if you are starting the meeting
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "false",
        disableShare: "false",
        noAudio: "false",
        noDisconnectAudio: "false"
    );
    if (IS_STARTING) {
        meeting = zoom.startMeeting(meetingOptions);
    } else {
        meeting = zoom.joinMeeting(meetingOptions);
    }

**Comment by 25LMartins** [comment]
> ```
>           var meetingOptions = ZoomMeetingOptions(
>     userId:
>         'username', //pass username for join meeting only --- Any name eg:- EVILRATT.
>     meetingId: 'xxxxxxx', //pass meeting id for join meeting only
>     meetingPassword: 'xxxx', //pass meeting password for join meeting only
>     disableDialIn: "true",
>     disableDrive: "true",
>     disableInvite: "true",
>     disableShare: "true",
>     noAudio: "false",
>     noDisconnectAudio: "false");
> 
> zoom.init(zoomOptions).then((results) {
>   print(results[0]);
>   if (results[0] == 0) {
>     zoom.onMeetingStateChanged.listen((status) {
>       print("[Meeting Status Stream] : " + status[0] + " - " + status[1]);
>     });
>     print("listen on event channel");
>     zoom.joinMeeting(meetingOptions).then((joinMeetingResult) {
>       print(joinMeetingResult);
>     });
>   }
> }).catchError((error) {
>   print("[Error Generated] : " + error);
> });
> ```
> 
> output flutter: listen on event channel flutter: true 4 flutter: [Meeting Status Stream] : MEETING_STATUS_CONNECTING - Connect to the meeting server flutter: [Meeting Status Stream] : MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, leave meeting status flutter: [Meeting Status Stream] : MEETING_STATUS_FAILED - Failed to connect the meeting server flutter: [Meeting Status Stream] : MEETING_STATUS_ENDED - Meeting ends
> 
> _Originally posted by @gowthaman13 in [#11 (comment)](https://github.com/25LucasAnselmo/gr_zoom/issues/11#issuecomment-1977081212)_

Try to use this params:


    var meetingOptions = new ZoomMeetingOptions(
        zoomAccessToken: ZAK_TOKEN, // See on zoom meeting website how to use
        zoomToken: ZOOM_TOKEN,
        userId: USERNAME,
        displayName: DISPLAYED_NAME,
        meetingId: MEETING_ID,
        meetingPassword: MEETING_PASS, // Only if you are starting the meeting
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "false",
        disableShare: "false",
        noAudio: "false",
        noDisconnectAudio: "false"
    );
    if (IS_STARTING) {
        meeting = zoom.startMeeting(meetingOptions);
    } else {
        meeting = zoom.joinMeeting(meetingOptions);
    }
    
Another point, please, dont create too many questions unecessarilly, but try to see the comments and respond the comments so as not to spam the space
