### ISSUE TITLE
Hello, Can i join to meeting as a host user? if there how i join as host user?

### ISSUE THREAD

**Issue by NaderDiab** [25LucasAnselmo/gr_zoom#3]

**Comment by 25LucasAnselmo** [comment]
Hey! I can do this on flutter_zoom project. What is your pub dev email?

**Comment by 25LucasAnselmo** [comment]
Hey! Do you mean start a meeting as host?

**Comment by NaderDiab** [comment]
Yes, I mean that when i join a meeting be host

**Comment by 25LucasAnselmo** [comment]
Ah, i got it. Well, I think if you send the zak token in the options, the user is accepted as a host... But i've never tested this before
![zak](https://github.com/25LucasAnselmo/gr_zoom/assets/20372417/a65fc740-3512-421f-8d53-a4d9b687e132)

**Comment by NaderDiab** [comment]
I sent it but nothing Changed.

**Comment by 25LucasAnselmo** [comment]
When you try this the user is accepted as a normal member?

**Comment by NaderDiab** [comment]
Yes, I still waiting the host  user to enter

**Comment by 25LucasAnselmo** [comment]
Are you using "Zoom().startMeeting" or "Zoom().joinMeeting" method?

**Comment by NaderDiab** [comment]
i using "Zoom().joinMeeting" method 
but i have 2 types of users (admin & normal user ) 
when i login as admin i send the zak to join the meeting as host if normal user i don't send the zak

**Comment by NaderDiab** [comment]
the meeting is created from portal not from mobile app and details for this meeting send to me from api

**Comment by 25LucasAnselmo** [comment]
Try using startMeeting, even though the meeting is open, it usually works. Also take a look at your Zoom account to see if you have any settings to enable co-hosts

**Comment by 25LucasAnselmo** [comment]
> i using "Zoom().joinMeeting" method but i have 2 types of users (admin & normal user ) when i login as admin i send the zak to join the meeting as host if normal user i don't send the zak

If user is admin, try using "startMeeting" sending the zak token

**Comment by NaderDiab** [comment]
Ok, I will try that,
Thank You very much.

**Comment by 25LucasAnselmo** [comment]
> Ok, I will try that, Thank You very much.

Youre welcome

**Comment by Anuj01111** [comment]
Meeting Status Stream: MEETING_STATUS_IDLE - No meeting is running

Pls Help Me....

**Comment by 25LucasAnselmo** [comment]
I updated version to 1.1.0+2. Check if in new version the meeting will work

The problems was Zoom Meeting min version, currently on 5.14.5
