### ISSUE TITLE
MEETING_STATUS_UNKNOWN - Version of ZoomSDK is too low

### ISSUE THREAD

**Issue by NaderDiab** [25LucasAnselmo/gr_zoom#4]

**Comment by NaderDiab** [comment]
[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.19045.3930], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.86.0)
[√] Connected device (4 available)
[√] Network resources

**Comment by 25LucasAnselmo** [comment]
I plan to update the zoom version in a few days

**Comment by NaderDiab** [comment]
ok ,Thank you

**Comment by Anuj01111** [comment]
Meeting Status Stream: MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, user leaves meeting.
Meeting Status Stream: MEETING_STATUS_UNKNOWN - Version of ZoomSDK is too low
Meeting Status Stream: MEETING_STATUS_IDLE - No meeting is running

**Comment by 25LucasAnselmo** [comment]
> ok ,Thank you

I updated version to 1.1.0+2. Check if in new version the meeting will work

The problems was Zoom Meeting min version, currently on 5.14.5

**Comment by NaderDiab** [comment]
ok ,thank you
