### ISSUE TITLE
MEETING_STATUS_FAILED 

### ISSUE THREAD

**Issue by Muhammed-Ramadan512** [25LucasAnselmo/gr_zoom#5]
MEETING_STATUS_FAILED it was working well but , suddenly it happen , can you support please

**Comment by Muhammed-Ramadan512** [comment]
[Meeting Status Polling] : MEETING_STATUS_FAILED -

**Comment by 25LucasAnselmo** [comment]
Hey! Well, do you get into the meeting (work for a moment) and suddenly fall down? Can you show your zoom params options?

**Comment by 25LucasAnselmo** [comment]
Are you using this params?

new ZoomMeetingOptions(
        zoomAccessToken: zakToken,
        zoomToken: meetingTokenToEnter,
        userId: userName,
        displayName: nameDisplayed,
        meetingId: meetingId,
        meetingPassword: pass, // Only if you will start meeting
        ...
)

**Comment by Muhammed-Ramadan512** [comment]
no i just use this parameter and was work good but suddenly didn,t work
appKey: TfHhRiMpRZ33yVhBcSO4ZIOi9Ew1eLsp2GJJ
appSecret: ZubMdRlYUeOa4HbQWFdcA8mxAamqYBvAVQS7

 ZoomOptions zoomOptions = new ZoomOptions(
      domain: "zoom.us",
      appKey: widget.appKey, //API KEY FROM ZOOM - Sdk API Key
      appSecret: widget.appSecret, //API SECRET FROM ZOOM - Sdk API Secret
    );

**Comment by Muhammed-Ramadan512** [comment]
https://github.com/25LucasAnselmo/gr_zoom/assets/48845841/774d4e68-5fcd-4185-8ea0-cec38e39fd00

that,s what happened with me

**Comment by 25LucasAnselmo** [comment]
Undestood. You are sending zak token on zoom options params?

**Comment by 25LucasAnselmo** [comment]
It seems some credential error

**Comment by Muhammed-Ramadan512** [comment]
But it was working fine , i didn't change any thing , can you provide me some credential to test if ot can work correctly.

**Comment by Muhammed-Ramadan512** [comment]
any update ??

> It seems some credential error

any updates

**Comment by Anuj01111** [comment]
https://github.com/25LucasAnselmo/gr_zoom/assets/155726816/1e47ceff-26ed-4293-a854-0b05a69558b4

Issue Pls Help me

**Comment by 25LucasAnselmo** [comment]
> VID-20240221-WA0000.mp4 
> Issue Pls Help me

There is any error status message? Even on debug console?

**Comment by Anuj01111** [comment]
> > VID-20240221-WA0000.mp4
> > Issue Pls Help me
> 
> There is any error status message? Even on debug console?


Meeting Status Stream: MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, user leaves meeting.
Meeting Status Stream: MEETING_STATUS_UNKNOWN - Version of ZoomSDK is too low
Meeting Status Stream: MEETING_STATUS_IDLE - No meeting is running

Complete Console Errer======

[log] ==== m0CNtaLmTXCFAWI60KN5Q
[log] ==== mPsvSEYcOI90sQ7WFU1MxziPARyEy0Pw
[log] ==== zoom.us
I/flutter (24137): zoom result [0, 0]
I/flutter (24137): result is true
D/libMEOW (24137): meow new tls: 0xb400006e11fb4780
D/libMEOW (24137): applied 1 plugins for [com.example.zoom_demo]:
D/libMEOW (24137):   plugin 1: [libMEOW_gift.so]: 0xb400006f0d3eed80
D/libMEOW (24137): rebuild call chain: 0xb400006e11fc3880
D/libMEOW (24137): meow delete tls: 0xb400006e11fb4780
I/CameraManagerExtImpl(24137): getInstance success!
I/CameraManagerExtImpl(24137): packagename is com.example.zoom_demo
I/OplusCameraManager(24137): saveOpPackageName, mOpPackageName: com.example.zoom_demo
I/OplusCameraManagerGlobal(24137): setClientInfo, packageName: com.example.zoom_demo, uid: 11137, pid: 24137
I/OplusCameraManagerGlobal(24137): Connecting to camera service
I/CameraManagerGlobal(24137): Connecting to camera service
D/OplusCameraUtils(24137): new OplusCameraUtils!
I/OplusCameraManagerGlobal(24137): setClientInfo, packageName: com.example.zoom_demo, uid: 11137, pid: 24137
I/OplusCameraManagerGlobal(24137): setClientInfo, packageName: com.example.zoom_demo, uid: 11137, pid: 24137
D/CompatibilityChangeReporter(24137): Compat change id reported: 147600208; UID 11137; state: ENABLED
I/AudioTrack(24137): set(): type=audio,case=1,attributes=1,content_type=1,usage=2,source=0,flags=0x800
D/AudioTrackExtImpl(24137): AudioTrackExtImpl init
D/AudioTrack(24137): set(): streamType -1, sampleRate 48000, format 0x1, channelMask 0x1, frameCount 4104, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
I/AudioTrack(24137): set(): 0xb400006f11ffdc00, Create AudioTrackThread, tid = 25396
D/ListServiceUtils(24137): mListServiceUtils::init CallingPid 24137
D/ListServiceUtils(24137): mListServiceUtils::init this 0xb400006e829fa540
D/AudioTrackExtImpl(24137): setAudioBoostTid
D/AudioTrackExtImpl(24137): oplusDumpValue PID is 24137  Tid is 25396
D/AudioTrackExtImpl(24137): setAudioBoostTid
D/AudioTrackExtImpl(24137): oplusDumpValue PID is 24137  Tid is 24137
D/AudioTrackExtImpl(24137): oplusDumpValue PID is 24137  Tid is 25396
I/AudioTrack(24137): createTrack_l(1244) on outputId(37) : 0xb400006f11ffdc00, mCblk = 0x6fca113000,  mLatency = 147, mAfLatency = 62, frameCount = 4104, mSampleRate = 48000, mFlags = 0, mReqFrameCount = 4104, mNotificationFramesAct = 2052
D/ListServiceUtils(24137): checkInListByUid module:change-futex-timeout uid:11137 cost 118us return 0
W/AudioTrack(24137): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(24137): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/AudioTrack(24137): stop(1244): prior state:STATE_STOPPED output 37 stream 0 session 4409
D/AudioTrack(24137): ~AudioTrack(1244), releasing mStatus =0 session id 4409 from 24137 on behalf of 24137
D/AudioTrack(24137): stop(1244): prior state:STATE_STOPPED output 37 stream 0 session 4409
I/AudioTrack(24137): stopAndJoinCallbacks(1244) done
D/AudioTrackExtImpl(24137): clearAudioBoostTid
D/AudioTrackExtImpl(24137): clearAudioBoostTid  pid 24137  tid 24137
D/AudioTrackExtImpl(24137): clearAudioBoostTid  pid 24137  tid 25396
D/AudioManager(24137): setMode mode=0 from com.example.zoom_demo
W/BluetoothAdapterExtImpl(24137): oplusSetMode register null!
V/SystemSensorManagerExtImpl(24137): RegisterListener icm4x6xx ACCELEROMETER type:1 delay:200000us by android.view.OrientationEventListener$SensorEventListenerImpl@ea86fb2 from com.example.zoom_demo
I/Quality (24137): ActivityThread: activityResume delay 489 com.example.zoom_demo 24137
D/VRI[MainActivity](24137): onFocusEvent false
D/CompatibilityChangeReporter(24137): Compat change id reported: 160794467; UID 11137; state: ENABLED
D/OpenGLRenderer(24137): --- Failed to create image decoder with message 'unimplemented'
D/libMEOW (24137): meow new tls: 0xb400006f0e4f0400
D/libMEOW (24137): applied 1 plugins for [com.example.zoom_demo]:
D/libMEOW (24137):   plugin 1: [libMEOW_gift.so]: 0xb400006f0d3eed80
D/libMEOW (24137): rebuild call chain: 0xb400006f0e70c480
D/libMEOW (24137): meow delete tls: 0xb400006f0e4f0400
E/OplusCustomizeRestrictionManager(24137): sInstance is null, start a new sInstance
D/CompatibilityChangeReporter(24137): Compat change id reported: 210923482; UID 11137; state: ENABLED
D/ScrollOptimizationHelper(24137): can't find the config file for optimizaiton
D/ScrollOptimizationHelper(24137): will not debug for debug is false
D/CompatibilityChangeReporter(24137): Compat change id reported: 171228096; UID 11137; state: ENABLED
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/ample.zoom_demo(24137): Compiler allocated 4186KB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/Quality (24137): ActivityThread: activityStart delay 1648 com.example.zoom_demo 24137
V/SystemSensorManagerExtImpl(24137): RegisterListener icm4x6xx ACCELEROMETER type:1 delay:200000us by android.view.OrientationEventListener$SensorEventListenerImpl@b2c4334 from com.example.zoom_demo
D/WindowManager(24137): Add to mViews: DecorView@c6ef008[ConfActivityNormal],pkg= com.example.zoom_demo
D/InputEventReceiver(24137): Input log is disabled
E/ANR_LOG (24137): Blocked msg = { when=+1s776ms what=159 target=android.app.ActivityThread$H obj=android.app.servertransaction.ClientTransaction@c86bbb7f } , cost  = 1776 ms
V/SystemSensorManagerExtImpl(24137): unRegisterListener by android.view.OrientationEventListener$SensorEventListenerImpl@b2c4334
D/CompatibilityChangeReporter(24137): Compat change id reported: 78294732; UID 11137; state: ENABLED
V/SystemSensorManagerExtImpl(24137): RegisterListener icm4x6xx ACCELEROMETER type:1 delay:200000us by android.view.OrientationEventListener$SensorEventListenerImpl@b2c4334 from com.example.zoom_demo
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.example.zoom_demo.MainActivity,This DecorView@6ce6737[MainActivity] change focus to false
I/flutter (24137): Meeting Status Polling: MEETING_STATUS_CONNECTING -
I/Quality (24137): Skipped: false 4 cost 73.945465 refreshRate 16287446 bit true processName com.example.zoom_demo
E/OplusBracketLog(24137): [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@30704b4
I/SurfaceView(24137): 11455148 onAttachedToWindow
D/BufferQueueConsumer(24137): [](id:5e4900000002,api:0,p:-1,c:24137) connect: controlledByApp=false
V/ZoomWindowDecorView(24137): setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.208597000
D/VRI[ConfActivityNormal](24137): registerCallbacksForSync syncBuffer=false
D/BLASTBufferQueue(24137): [VRI[ConfActivityNormal][com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal]#2](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=35545961047117(auto) mPendingTransactions.size=0 graphicBufferId=103667625623557 transform=0
D/VRI[ConfActivityNormal](24137): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
W/Parcel  (24137): Expecting binder but got null!
D/VRI[ConfActivityNormal](24137): draw finished.
I/flutter (24137): Meeting Status Stream: MEETING_STATUS_CONNECTING - Connect to the meeting server.
D/WindowManager(24137): Add to mViews: android.widget.PopupWindow$PopupDecorView{37c5a9d V.E...... R.....I. 0,0-0,0 viewInfo = AutoLayoutViewInfo{mIsImageType=false, mIsFlatView=false, mWidthType=1, mHeightType=1, mScaleType=null, mFillBackgroundPattern=1, mNeedStretchItems=false, mMeasureChanged=false, mNewMeasuredHeight=0, mOldMeasuredHeight=0, mExtraInfo=}},pkg= com.example.zoom_demo
D/InputEventReceiver(24137): Input log is disabled
I/Quality (24137): Skipped: false 11 cost 192.24341 refreshRate 16666667 bit true processName com.example.zoom_demo
E/OplusBracketLog(24137): [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@8490399
D/BufferQueueConsumer(24137): [](id:5e4900000003,api:0,p:-1,c:24137) connect: controlledByApp=false
D/VRI[PopupWindow:52a8574](24137): registerCallbacksForSync syncBuffer=false
D/VRI[PopupWindow:52a8574](24137): draw finished.
D/VRI[ConfActivityNormal](24137): registerCallbacksForSync syncBuffer=false
D/VRI[ConfActivityNormal](24137): Received frameCommittedCallback lastAttemptedDrawFrameNum=3 didProduceBuffer=true syncBuffer=false
D/VRI[ConfActivityNormal](24137): draw finished.
D/VRI[PopupWindow:52a8574](24137): registerCallbacksForSync syncBuffer=false
D/VRI[PopupWindow:52a8574](24137): draw finished.
D/VRI[ConfActivityNormal](24137): onFocusEvent true
D/VRI[MainActivity](24137): dispatchAppVisibility visible:false
I/SurfaceView(24137): 241429872 surfaceDestroyed
D/BLASTBufferQueue(24137): [SurfaceView[com.example.zoom_demo/com.example.zoom_demo.MainActivity]#1](f:0,a:1) destructor()
D/BufferQueueConsumer(24137): [SurfaceView[com.example.zoom_demo/com.example.zoom_demo.MainActivity]#1(BLAST Consumer)1](id:5e4900000001,api:0,p:-1,c:24137) disconnect
D/SurfaceView(24137): 212849462positionLost mSurfaceControl is null return;
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006f11eb7200, mContext=0xb400006f0e2ad740
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f15056f00, surface=NULL
D/BLASTBufferQueue(24137): [VRI[MainActivity][com.example.zoom_demo/com.example.zoom_demo.MainActivity]#0](f:0,a:1) destructor()
D/BufferQueueConsumer(24137): [VRI[MainActivity][com.example.zoom_demo/com.example.zoom_demo.MainActivity]#0(BLAST Consumer)0](id:5e4900000000,api:0,p:-1,c:24137) disconnect
D/VRI[MainActivity](24137): setWindowStopped stopped:true
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal,This DecorView@c6ef008[ConfActivityNormal] change focus to true
I/flutter (24137): Meeting Status Polling: MEETING_STATUS_CONNECTING -
I/flutter (24137): Meeting Status Stream: MEETING_STATUS_DISCONNECTING - Disconnect the meeting server, user leaves meeting.
V/SystemSensorManagerExtImpl(24137): unRegisterListener by android.view.OrientationEventListener$SensorEventListenerImpl@ea86fb2
D/VRI[ConfActivityNormal](24137): onFocusEvent false
V/SystemSensorManagerExtImpl(24137): unRegisterListener by android.view.OrientationEventListener$SensorEventListenerImpl@b2c4334
D/VRI[MainActivity](24137): dispatchAppVisibility visible:true
D/libMEOW (24137): meow new tls: 0xb400006f0e40dd80
D/libMEOW (24137): applied 1 plugins for [com.example.zoom_demo]:
D/libMEOW (24137):   plugin 1: [libMEOW_gift.so]: 0xb400006f0d3eed80
D/libMEOW (24137): rebuild call chain: 0xb400006f0e506d00
D/libMEOW (24137): meow delete tls: 0xb400006f0e40dd80
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
I/oplus.android.OplusFrameworkFactoryImpl(24137): get feature:IOplusDynamicVsyncFeature
D/WindowManager(24137): Add to mViews: DecorView@580810b[MeetingEndMessageActivity],pkg= com.example.zoom_demo
D/InputEventReceiver(24137): Input log is disabled
D/WindowManager(24137): Add to mViews: DecorView@48af18[MeetingEndMessageActivity],pkg= com.example.zoom_demo
D/InputEventReceiver(24137): Input log is disabled
D/VRI[MainActivity](24137): setWindowStopped stopped:false
I/Quality (24137): Skipped: false 5 cost 87.78861 refreshRate 16289968 bit true processName com.example.zoom_demo
E/OplusBracketLog(24137): [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@43422e7
D/BufferQueueConsumer(24137): [](id:5e4900000004,api:0,p:-1,c:24137) connect: controlledByApp=false
E/IPCThreadState(24137): attemptIncStrongHandle(56): Not supported
V/ZoomWindowDecorView(24137): setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.92307723
D/VRI[MeetingEndMessageActivity](24137): registerCallbacksForSync syncBuffer=false
D/BLASTBufferQueue(24137): [VRI[MeetingEndMessageActivity][com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity]#4](f:0,a:1) acquireNextBufferLocked size=478x295 mFrameNumber=1 applyTransaction=true mTimestamp=35548126585271(auto) mPendingTransactions.size=0 graphicBufferId=103667625623566 transform=0
D/VRI[MeetingEndMessageActivity](24137): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
W/Parcel  (24137): Expecting binder but got null!
D/VRI[MeetingEndMessageActivity](24137): draw finished.
E/OplusBracketLog(24137): [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@4a5a4c4
D/BufferQueueConsumer(24137): [](id:5e4900000005,api:0,p:-1,c:24137) connect: controlledByApp=false
V/ZoomWindowDecorView(24137): setLastReportedMergedConfiguration mZoomDisplayHeight: 2400 getDecorView.4763416
D/VRI[MeetingEndMessageActivity](24137): registerCallbacksForSync syncBuffer=false
D/VRI[MeetingEndMessageActivity](24137): draw finished.
D/BufferQueueConsumer(24137): [](id:5e4900000006,api:0,p:-1,c:24137) connect: controlledByApp=false
D/BufferQueueConsumer(24137): [](id:5e4900000007,api:0,p:-1,c:24137) connect: controlledByApp=false
I/SurfaceView(24137): 241429872 visibleChanged -- surfaceCreated
I/SurfaceView(24137): 241429872 surfaceChanged -- format=4 w=1080 h=2400
D/VRI[MainActivity](24137): registerCallbacksForSync syncBuffer=false
D/BLASTBufferQueue(24137): [VRI[MainActivity][com.example.zoom_demo/com.example.zoom_demo.MainActivity]#6](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=35548167005194(auto) mPendingTransactions.size=0 graphicBufferId=103667625623571 transform=0
D/VRI[MainActivity](24137): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
D/VRI[MainActivity](24137): draw finished.
I/Quality (24137): Skipped: false 3 cost 64.24774 refreshRate 16286788 bit true processName com.example.zoom_demo
D/VRI[MeetingEndMessageActivity](24137): registerCallbacksForSync syncBuffer=false
D/VRI[MeetingEndMessageActivity](24137): Received frameCommittedCallback lastAttemptedDrawFrameNum=2 didProduceBuffer=true syncBuffer=false
D/VRI[MeetingEndMessageActivity](24137): draw finished.
D/BLASTBufferQueue(24137): [SurfaceView[com.example.zoom_demo/com.example.zoom_demo.MainActivity]#7](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=35548204579733(auto) mPendingTransactions.size=0 graphicBufferId=103667625623572 transform=0
I/Quality (24137): Skipped: false 1 cost 27.911827 refreshRate 16283950 bit true processName com.example.zoom_demo
D/VRI[MeetingEndMessageActivity](24137): registerCallbacksForSync syncBuffer=false
D/VRI[MeetingEndMessageActivity](24137): draw finished.
I/flutter (24137): Meeting Status Stream: MEETING_STATUS_UNKNOWN - Version of ZoomSDK is too low
I/ample.zoom_demo(24137): Compiler allocated 5180KB to compile void android.view.ViewRootImpl.performTraversals()
D/VRI[MeetingEndMessageActivity](24137): onFocusEvent true
D/VRI[PopupWindow:52a8574](24137): dispatchAppVisibility visible:false
D/VRI[ConfActivityNormal](24137): dispatchAppVisibility visible:false
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006eac9fe400, mContext=0xb400006f0e4e2440
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e87ee00, surface=NULL
D/BLASTBufferQueue(24137): [VRI[PopupWindow:52a8574][PopupWindow:52a8574]#3](f:0,a:0) destructor()
D/BufferQueueConsumer(24137): [VRI[PopupWindow:52a8574][PopupWindow:52a8574]#3(BLAST Consumer)3](id:5e4900000003,api:0,p:-1,c:24137) disconnect
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006f11fe2a00, mContext=0xb400006f0e72cfc0
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e87ec00, surface=NULL
D/BLASTBufferQueue(24137): [VRI[ConfActivityNormal][com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal]#2](f:0,a:1) destructor()
D/BufferQueueConsumer(24137): [VRI[ConfActivityNormal][com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal]#2(BLAST Consumer)2](id:5e4900000002,api:0,p:-1,c:24137) disconnect
D/VRI[ConfActivityNormal](24137): setWindowStopped stopped:true
D/VRI[PopupWindow:52a8574](24137): setWindowStopped stopped:true
D/OplusScrollToTopManager(24137): PopupWindow:52a8574,window dying
D/OplusScrollToTopManager(24137): PopupWindow:52a8574,unregisterSystemUIBroadcastReceiver
D/OplusScrollToTopManager(24137): PopupWindow:52a8574, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@837a88e
V/ZoomWindowDecorView(24137): removeZoomView
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006eac9fe400, mContext=0xb400006f0e4e2440
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e87ee00, surface=NULL
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal,window dying
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal,unregisterSystemUIBroadcastReceiver
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.ConfActivityNormal, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@b448cc0
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e87ee00, surface=NULL
D/CursorFeedback(24137): editorDetachFromWindow android.widget.Editor@445b4ec
V/ZoomWindowDecorView(24137): removeZoomView
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006f11fe2a00, mContext=0xb400006f0e72cfc0
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e87ec00, surface=NULL
I/Quality (24137): Skipped: true 10 cost 166.45409 refreshRate 16298430 bit true processName com.example.zoom_demo
I/WebViewFactory(24137): Loading com.google.android.webview version 117.0.5938.60 (code 593806031)
W/ziparchive(24137): Unable to open '/product/app/TrichromeLibrary/TrichromeLibrary.dm': No such file or directory
W/ziparchive(24137): Unable to open '/product/app/TrichromeLibrary/TrichromeLibrary.dm': No such file or directory
W/ample.zoom_demo(24137): Entry not found
D/nativeloader(24137): InitLlndkLibrariesProduct: libEGL.so:libGLESv1_CM.so:libGLESv2.so:libGLESv3.so:libRS.so:libandroid_net.so:libbinder_ndk.so:libc.so:libcgrouprc.so:libclang_rt.asan-aarch64-android.so:libclang_rt.asan-arm-android.so:libdl.so:libft2.so:liblog.so:libm.so:libmediandk.so:libnativewindow.so:libneuralnetworks.so:libselinux.so:libsync.so:libvndksupport.so:libvulkan.so
D/nativeloader(24137): Configuring product-clns-7 for unbundled product apk /product/app/TrichromeLibrary/TrichromeLibrary.apk. target_sdk_version=34, uses_libraries=ALL, library_path=/product/app/WebViewGoogle/lib/arm64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/product/lib64:/system/product/lib64
D/nativeloader(24137): Extending system_exposed_libraries: libapuwareapusys.mtk.so:libapuwareapusys_v2.mtk.so:libapuwarexrp.mtk.so:libapuwarexrp_v2.mtk.so:libapuwareutils.mtk.so:libapuwareutils_v2.mtk.so:libapuwarehmp.mtk.so:libmcv_runtime_usdk.mtk.so:libneuron_graph_delegate.mtk.so:libneuronusdk_adapter.mtk.so:libtflite_mtk.mtk.so:libarmnn_ndk.mtk.so:libcmdl_ndk.mtk.so:libnir_neon_driver_ndk.mtk.so:libmvpu_runtime.mtk.so:libmvpu_runtime_pub.mtk.so:libmvpu_engine_pub.mtk.so:libmvpu_pattern_pub.mtk.so:libmvpuop_mtk_cv.mtk.so:libmvpuop_mtk_nn.mtk.so:libSloganJni.oplus.so:libsuperNight.oplus.so
D/nativeloader(24137): InitVndkspLibrariesProduct: android.hardware.common-V1-ndk_platform.so:android.hardware.graphics.common-V1-ndk_platform.so:android.hardware.graphics.common@1.0.so:android.hardware.graphics.common@1.1.so:android.hardware.graphics.common@1.2.so:android.hardware.graphics.mapper@2.0.so:android.hardware.graphics.mapper@2.1.so:android.hardware.graphics.mapper@3.0.so:android.hardware.graphics.mapper@4.0.so:android.hardware.renderscript@1.0.so:android.hidl.memory.token@1.0.so:android.hidl.memory@1.0-impl.so:android.hidl.memory@1.0.so:android.hidl.safe_union@1.0.so:libRSCpuRef.so:libRSDriver.so:libRS_internal.so:libbacktrace.so:libbase.so:libbcinfo.so:libblas.so:libc++.so:libcompiler_rt.so:libcutils.so:libgralloctypes.so:libhardware.so:libhidlbase.so:libhidlmemory.so:libion.so:libjsoncpp.so:liblzma.so:libprocessgroup.so:libunwindstack.so:libutils.so:libutilscallstack.so:libz.so
D/nativeloader(24137): Configuring product-clns-8 for unbundled product apk /product/app/WebViewGoogle/WebViewGoogle.apk. target_sdk_version=34, uses_libraries=, library_path=/product/app/WebViewGoogle/lib/arm64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64, permitted_path=/data:/mnt/expand:/product/lib64:/system/product/lib64
I/cr_WVCFactoryProvider(24137): Loaded version=117.0.5938.60 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(24137): Successfully loaded native library
I/cr_CachingUmaRecorder(24137): Flushed 7 samples from 7 histograms, 0 samples were dropped.
E/chromium(24137): [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com.example.zoom_demo/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
E/chromium(24137): [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
D/CompatibilityChangeReporter(24137): Compat change id reported: 214741472; UID 11137; state: ENABLED
I/Quality (24137): Skipped: true 15 cost 255.51654 refreshRate 16291186 bit true processName com.example.zoom_demo
D/VRI[MeetingEndMessageActivity](24137): onFocusEvent false
W/ample.zoom_demo(24137): Accessing hidden field Landroid/content/pm/ApplicationInfo;->primaryCpuAbi:Ljava/lang/String; (unsupported, reflection, allowed)
D/VRI[MainActivity](24137): onFocusEvent true
I/Quality (24137): Skipped: false 1 cost 17.675545 refreshRate 16285330 bit true processName com.example.zoom_demo
D/VRI[MeetingEndMessageActivity](24137): setWindowStopped stopped:true
D/VRI[MeetingEndMessageActivity](24137): setWindowStopped stopped:true
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity,window dying
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity,unregisterSystemUIBroadcastReceiver
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@202a3d1
V/ZoomWindowDecorView(24137): removeZoomView
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006eac9de600, mContext=0xb400006f0e506ac0
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e31ea00, surface=NULL
D/BLASTBufferQueue(24137): [VRI[MeetingEndMessageActivity][com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity]#4](f:0,a:1) destructor()
D/BufferQueueConsumer(24137): [VRI[MeetingEndMessageActivity][com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity]#4(BLAST Consumer)4](id:5e4900000004,api:0,p:-1,c:24137) disconnect
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity,window dying
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity,unregisterSystemUIBroadcastReceiver
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity, unregisterSystemUIBroadcastReceiver failed java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@6f879d3
V/ZoomWindowDecorView(24137): removeZoomView
D/OpenGLRenderer(24137): RenderProxy::destroy: this=0xb400006f11fe2c00, mContext=0xb400006f0e40d2c0
D/OpenGLRenderer(24137): SkiaOpenGLPipeline::setSurface: this=0xb400006f0e84bd00, surface=NULL
D/BLASTBufferQueue(24137): [VRI[MeetingEndMessageActivity][com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity]#5](f:0,a:0) destructor()
D/BufferQueueConsumer(24137): [VRI[MeetingEndMessageActivity][com.example.zoom_demo/com.zipow.videobox.MeetingEndMessageActivity]#5(BLAST Consumer)5](id:5e4900000005,api:0,p:-1,c:24137) disconnect
I/Quality (24137): Skipped: false 1 cost 17.085693 refreshRate 16285942 bit true processName com.example.zoom_demo
D/VRI[MeetingEndMessageActivity](24137): dispatchAppVisibility visible:false
D/VRI[MeetingEndMessageActivity](24137): dispatchAppVisibility visible:false
I/flutter (24137): Meeting Status Stream: MEETING_STATUS_IDLE - No meeting is running
D/OplusScrollToTopManager(24137): com.example.zoom_demo/com.example.zoom_demo.MainActivity,This DecorView@6ce6737[MainActivity] change focus to true

**Comment by 25LucasAnselmo** [comment]
I updated version to 1.1.0+2. Check if in new version the meeting will work

The problems was Zoom Meeting min version, currently on 5.14.5
