### ISSUE TITLE
please join this meeting with an official zoom meeting cleint (error code 6601)

### ISSUE THREAD

**Issue by Muhammed-Ramadan512** [25LucasAnselmo/gr_zoom#6]
i get this message when i try to join meeting 
please join this meeting with an official zoom meeting cleint (error code 6601)

![Screenshot_1708338320](https://github.com/25LucasAnselmo/gr_zoom/assets/48845841/6099d93d-63dc-49d8-9eea-f7c67ad7fa12)

**Comment by Anuj01111** [comment]
Same Issue 

https://github.com/25LucasAnselmo/gr_zoom/assets/155726816/9685b61f-7299-4f21-af11-ec1f6f9230c1

**Comment by 25LucasAnselmo** [comment]
Hey. Ill check this issue

**Comment by 25LucasAnselmo** [comment]
> i get this message when i try to join meeting please join this meeting with an official zoom meeting cleint (error code 6601)
> 
> ![Screenshot_1708338320](https://private-user-images.githubusercontent.com/48845841/305949928-6099d93d-63dc-49d8-9eea-f7c67ad7fa12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTE4NDgsIm5iZiI6MTcwODk1MTU0OCwicGF0aCI6Ii80ODg0NTg0MS8zMDU5NDk5MjgtNjA5OWQ5M2QtNjNkYy00OWQ4LTllZWEtZjdjNjdhZDdmYTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDEyNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGJmN2NmMGFmNTJjZTk1NDQ2ZDQ4YTFkOGJkMTAzNDNhYzFlYzgyZDVjYjAyOTU4NDdhNTkxNmE1OTA1ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R-DV_RcgVvWxEpKzK-icM_GfcJpwV5yGFOlwWCwZ2t4)

Is your Zoom appkey and appsecret correct? This modal is normally showed when we have some issue with credencials

**Comment by 25LucasAnselmo** [comment]
Can you check this post?

https://devforum.zoom.us/t/sample-app-failed-to-join-meeting-because-of-error-6601/101751

**Comment by 25LucasAnselmo** [comment]
I updated version to 1.1.0+2. Check if in new version the meeting will work

The problems was Zoom Meeting min version, currently on 5.14.5
