### ISSUE TITLE
Value of type 'MobileRTCAuthService' has no member 'clientKey'

### ISSUE THREAD

**Issue by GowthamScripts** [25LucasAnselmo/gr_zoom#9]
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Value of type 'MobileRTCAuthService' has no member 'clientKey'
/Users/apple/.pub-cache/hosted/pub.dev/gr_zoom-1.2.0+2/ios/Classes/SwiftZoomPlugin.swift:86:18

Swift Compiler Error (Xcode): Value of type 'MobileRTCAuthService' has no member 'clientSecret'
/Users/apple/.pub-cache/hosted/pub.dev/gr_zoom-1.2.0+2/ios/Classes/SwiftZoomPlugin.swift:89:18

**Comment by 25LucasAnselmo** [comment]
> Could not build the precompiled application for the device. Swift Compiler Error (Xcode): Value of type 'MobileRTCAuthService' has no member 'clientKey' /Users/apple/.pub-cache/hosted/pub.dev/gr_zoom-1.2.0+2/ios/Classes/SwiftZoomPlugin.swift:86:18
> 
> Swift Compiler Error (Xcode): Value of type 'MobileRTCAuthService' has no member 'clientSecret' /Users/apple/.pub-cache/hosted/pub.dev/gr_zoom-1.2.0+2/ios/Classes/SwiftZoomPlugin.swift:89:18

Hey. Man, try using 1.1.0+2 version

**Comment by 25LucasAnselmo** [comment]
> Could not build the precompiled application for the device. Swift Compiler Error (Xcode): Value of type 'MobileRTCAuthService' has no member 'clientKey' /Users/apple/.pub-cache/hosted/pub.dev/gr_zoom-1.2.0+2/ios/Classes/SwiftZoomPlugin.swift:86:18
> 
> Swift Compiler Error (Xcode): Value of type 'MobileRTCAuthService' has no member 'clientSecret' /Users/apple/.pub-cache/hosted/pub.dev/gr_zoom-1.2.0+2/ios/Classes/SwiftZoomPlugin.swift:89:18

Fixed in 1.2.0+4 version
